from __future__ import annotations

RODIN_FREE_TRIAL_KEY = "vibecoding"

BLENDER_MCP_INSTANCE_SCHEMA = "blender-mcp-instance/1"

BLENDER_MCP_BRIDGE_PROTOCOL = "blender-mcp-bridge/2"

BLENDER_MCP_DEFAULT_HOST = "127.0.0.1"

BLENDER_MCP_DEFAULT_PORT = 9876

BLENDER_MCP_HEARTBEAT_SECONDS = 2.0

BLENDER_MCP_DEFAULT_LEASE_SECONDS = 120.0

BLENDER_MCP_MIN_LEASE_SECONDS = 30.0

BLENDER_MCP_MAX_LEASE_SECONDS = 600.0

BLENDER_MCP_ACCEPT_POLL_SECONDS = 1.0
